application:
    image: debian:jessie
    env_file: docker-env
    volumes:
        - ~/vbox/www:/var/www
        - ~/vbox/conf/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - ~/vbox/conf/sites:/etc/apache2/sites-enabled
    tty: true

web:
    build: apache
    ports:
        - "80:80"
    volumes_from:
        - application
    env_file: docker-env
    links:
        - mysql

mysql:
    image: mariadb:latest
    env_file: docker-env
    ports:
        - "3306:3306"
    tty: true